const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Plugins.TiledBg,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Text,
		C3.Behaviors.wrap,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim
	];
};
self.C3_JsPropNameTable = [
	{"8Direction": 0},
	{BoundToLayout: 0},
	{ScrollTo: 0},
	{Player: 0},
	{TiledBackground: 0},
	{Mouse: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{Text: 0},
	{EnemyHP: 0},
	{randomnumb: 0},
	{Wrap: 0},
	{Enemy: 0},
	{Keyboard: 0},
	{EnemyBullet: 0},
	{WinText: 0},
	{Audio: 0},
	{PlayerHP: 0},
	{Score: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Mouse: class extends self.IInstance {},
	Bullet: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	EnemyBullet: class extends self.ISpriteInstance {},
	WinText: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {}
}